version: '3.8'
services:
  postgres:
    image: postgres
    container_name: goober-postgres
    environment:
      POSTGRES_DB: goober
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
