version: '3'

services:
  db:
    image: postgres:14
    container_name: goober
    tty: true
    environment:
      POSTGRES_DB: goober
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1.sql
volumes:
  postgres-data:
