spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/goober
  datasource:
    url: jdbc:postgresql://localhost:5432/goober
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  mail:
    host: smp.gmail.com
    port: 587
    username: meusitewebmail@gmail.com
    password: cwmz kiro oyhy swxu
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
myapp:
  secret:
    token: ${MY_SECRET_TOKEN:alfabeto}